-- Autor: Ronald Garcia Guerrero 
INSERT INTO CLIENTES (
	NOMBRE,
    APELLIDOS,
    DIRECCION, 
    POBLACION, 
    CODIGOPOSTAL, 
    TELEFONO, 
    EMAIL) 
VALUES ('PEPE', 'PEREZ PEREZ', 'CALLE CORREDURIA 1', 'SEVILLA', '41001', 655555555, 'PEPE@RON.COM');

INSERT INTO CLIENTES (
	NOMBRE,
    APELLIDOS,
    DIRECCION, 
    POBLACION, 
    CODIGOPOSTAL, 
    TELEFONO, 
    EMAIL) 
VALUES ('CHEMA', 'GARCIA OSUNA', 'CALLE PARRAS 1', 'SEVILLA', '41002', 644444444, 'CHEMA@RON.COM');

INSERT INTO CLIENTES (
	NOMBRE,
    APELLIDOS,
    DIRECCION, 
    POBLACION, 
    CODIGOPOSTAL, 
    TELEFONO, 
    EMAIL) 
VALUES ('NESTOR', 'LOZANO LOPEZ', 'CALLE RELATOR 1', 'SEVILLA', '41005', 633333333, 'NESTOR@RON.COM');


INSERT INTO CLIENTES (
	NOMBRE,
    APELLIDOS,
    DIRECCION, 
    POBLACION, 
    CODIGOPOSTAL, 
    TELEFONO, 
    EMAIL) 
VALUES ('ADRIAN', 'MAINEZ MAINEZ', 'CALLE MACARENA 1', 'SEVILLA', '41003', 611111111, 'ADRIAN@RON.COM');

INSERT INTO CLIENTES (
	NOMBRE,
    APELLIDOS,
    DIRECCION, 
    POBLACION, 
    CODIGOPOSTAL, 
    TELEFONO, 
    EMAIL) 
VALUES ('JOSE MANUEL', 'ALVARADO ALVARADO', 'CALLE POZO 1', 'SEVILLA', '41004', 622222222, 'JOSE@RON.COM');

INSERT INTO CLIENTES (
	NOMBRE,
    APELLIDOS,
    DIRECCION, 
    POBLACION, 
    CODIGOPOSTAL, 
    TELEFONO, 
    EMAIL) 
VALUES ('ESTEFANIA', 'VAZQUEZ VAZQUEZ', 'CALLE FERIA TORRES', 'SEVILLA', '41006', 677777777, 'ESTEFANIA@RON.COM');

INSERT INTO CLIENTES (
	NOMBRE,
    APELLIDOS,
    DIRECCION, 
    POBLACION, 
    CODIGOPOSTAL, 
    TELEFONO, 
    EMAIL) 
VALUES ('JESUS', 'DENIZ DENIZ', 'CALLE SAN LUIS 200', 'SEVILLA', '41007', 688888888, 'JESUS@RON.COM');

INSERT INTO CLIENTES (
	NOMBRE,
    APELLIDOS,
    DIRECCION, 
    POBLACION, 
    CODIGOPOSTAL, 
    TELEFONO, 
    EMAIL) 
VALUES ('BELEN', 'RODRIGUEZ AMARO', 'CALLE JESUS DEL GRAN PODER 1', 'SEVILLA', '41008', 699999999, 'BELEN@RON.COM');

INSERT INTO CLIENTES (
	NOMBRE,
    APELLIDOS,
    DIRECCION, 
    POBLACION, 
    CODIGOPOSTAL, 
    TELEFONO, 
    EMAIL) 
VALUES ('ANGEL', 'PERNI LLORENTE', 'CALLE JESUS DEL GRAN PODER 1', 'SEVILLA', '41008', 60000000, 'ANGEL@RON.COM');