DROP TABLE CLIENTES;
CREATE TABLE CLIENTES (
	ID_CLIENTES INT AUTO_INCREMENT,
	NOMBRE TEXT,
    APELLIDOS TEXT,
    DIRECCION TEXT, 
    POBLACION TEXT, 
    CODIGOPOSTAL TEXT, 
    TELEFONO INT, 
    EMAIL TEXT,
    CONSTRAINT PRIMARY KEY (ID_CLIENTES)
);